#!/bin/bash

# get list of VMs on the node
VMIDs=$(qm list| awk '/[0-9]/ {print $1}')

# ask them to shutdown
for VM in $VMIDs
do
    echo "qm shutdown $VM"
    qm shutdown $VM
done


#wait until they're done (and down)
for VM in $VMIDs
do
    while [[ $(qm status $VM) =~ running ]] ; do
        sleep 1
    done
done

## do the reboot
echo "shutdown -r now"
init 0

