#!/bin/bash
# sk,24,01,23 Container eingebaut

# get list of VMs on the node
VMIDs=$(qm list| awk '/[0-9]/ {print $1}')

# ask them to shutdown
for VM in $VMIDs
do
    echo "qm shutdown $VM"
    qm shutdown $VM
done

# get list of CTs on the node
CTIDs=$(pct list| awk '/[0-9]/ {print $1}')
for CT in $CTIDs
do
    echo "pct shutdown $CT"
    pct shutdown $CT
done


#wait until they're done (and down)
for VM in $VMIDs
do
    while [[ $(qm status $VM) =~ running ]] ; do
        sleep 1
    done
done

#wait until they're done (and down)
for CT in $CTIDs
do
    while [[ $(pct status $CT) =~ running ]] ; do
        sleep 1
    done
done


## shutdown pve
echo "init 0"
init 0

